"use client";
import {useState} from "react";
import {Activity,ArrowDownRight,ArrowRight,Award,Check,ChevronRight,CircuitBoard,Gauge,Menu,Microscope,Phone,ScanLine,Settings2,ShieldCheck,Sparkles,Wrench,X,Zap} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
const whatsapp="584222872237";
const services=[
 {n:"01",title:"Diagnóstico electrónico",text:"Lectura avanzada, análisis de señales y diagnóstico preciso en gasolina, diésel y eléctricos.",icon:ScanLine,image:"https://res.cloudinary.com/dgp7uhps3/image/upload/v1788231885/ChatGPT_Image_1_sept_2026_00_01_50_2_nzmhqo.png"},
 {n:"02",title:"Reparación de módulos",text:"Diagnóstico y reparación de ECU, ABS, BCM, TIPM, tableros y clusters.",icon:CircuitBoard,image:"https://res.cloudinary.com/dgp7uhps3/image/upload/v1788231894/ChatGPT_Image_1_sept_2026_00_01_42_1_uxtqtq.png"},
 {n:"03",title:"Tuning & programación ECU",text:"Calibración con HP Tuners, BitEdit y VFT Tuning. Reprogramación profesional.",icon:Gauge,image:"https://res.cloudinary.com/dgp7uhps3/image/upload/v1788231889/ChatGPT_Image_1_sept_2026_00_02_08_4_1_kdnntp.png"},
 {n:"04",title:"Inyección EFI / GDI",text:"Entonación y prueba de inyectores. Limpieza y descarbonización de válvulas.",icon:Activity,image:"https://res.cloudinary.com/dgp7uhps3/image/upload/v1788231895/ChatGPT_Image_1_sept_2026_00_02_07_3_ou7mju.png"},
 {n:"05",title:"Electricidad & cableado",text:"Localización de fallas, reparación de cableado y trazado con osciloscopio.",icon:Zap,image:"https://res.cloudinary.com/dgp7uhps3/image/upload/v1788231889/ChatGPT_Image_1_sept_2026_00_02_19_6_1_vikp0j.png"},
 {n:"06",title:"Diagnóstico diésel 12V / 24V",text:"Vehículos livianos, camionetas y equipos pesados con instrumentación dedicada.",icon:Settings2,image:"https://res.cloudinary.com/dgp7uhps3/image/upload/v1788231893/ChatGPT_Image_1_sept_2026_00_02_17_5_1_nm7zon.png"},
 {n:"07",title:"Eliminación EGR (EGR OFF)",text:"Anulación electrónica profesional para aplicaciones permitidas, competición u off-road, según normativa local.",icon:Wrench,image:"https://res.cloudinary.com/dgp7uhps3/image/upload/v1788231888/ChatGPT_Image_1_sept_2026_00_02_26_7_1_qt1x2c.png"}
];
const brands=["TOYOTA","FORD","CHEVROLET","MITSUBISHI","JEEP","DODGE","CHRYSLER"];
const works=[
 {image:"/work/hptuners.webp",tag:"PROGRAMACIÓN",title:"Calibración HP Tuners"},{image:"/work/toyota.webp",tag:"DIAGNÓSTICO",title:"Electrónica Toyota"},{image:"/work/abs.webp",tag:"LABORATORIO",title:"Reparación de módulo ABS"},{image:"/work/bcm.webp",tag:"ELECTRÓNICA",title:"Intervención BCM / TIPM"},{image:"/work/chevrolet.webp",tag:"MULTIMARCA",title:"Diagnóstico Chevrolet"},{image:"/work/mitsubishi.webp",tag:"MULTIMARCA",title:"Diagnóstico Mitsubishi"},{image:"/work/jeep.webp",tag:"PROGRAMACIÓN",title:"Sistemas Jeep / Chrysler"},{image:"/work/cableado.webp",tag:"ELECTRICIDAD",title:"Reparación de cableado"}
];
function Quote({label="Solicitar diagnóstico",className=""}:{label?:string,className?:string}){const[vehicle,setVehicle]=useState("");const[service,setService]=useState("");const[details,setDetails]=useState("");const[mode,setMode]=useState("");const send=()=>{const msg=`Hola Autotrónica Go Diag. Quiero solicitar una evaluación.\n\nVehículo: ${vehicle||"A confirmar"}\nServicio: ${service||"A confirmar"}\nModalidad: ${mode||"A confirmar"}\nDetalle / síntomas: ${details||"Sin detalle"}`;window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(msg)}`,"_blank")};return <Dialog><DialogTrigger className={className}>{label}<ArrowRight size={17}/></DialogTrigger><DialogContent className="quote-modal"><DialogHeader><DialogTitle>Prepará tu diagnóstico</DialogTitle></DialogHeader><p className="modal-lead">Completá estos datos. Un especialista revisará tu caso antes de confirmar el alcance y presupuesto.</p><div className="form-grid"><label><span>Marca, modelo y año</span><Input value={vehicle} onChange={e=>setVehicle(e.target.value)} placeholder="Ej. Toyota Corolla 2022"/></label><label><span>¿Qué necesitás?</span><Select value={service} onValueChange={setService}><SelectTrigger><SelectValue placeholder="Seleccionar servicio"/></SelectTrigger><SelectContent>{services.map(s=><SelectItem key={s.title} value={s.title}>{s.title}</SelectItem>)}</SelectContent></Select></label><label><span>Modalidad</span><Select value={mode} onValueChange={setMode}><SelectTrigger><SelectValue placeholder="Seleccionar modalidad"/></SelectTrigger><SelectContent><SelectItem value="En el taller">En el taller</SelectItem><SelectItem value="A domicilio">Diagnóstico a domicilio</SelectItem><SelectItem value="Asesoramiento">Necesito asesoramiento</SelectItem></SelectContent></Select></label><label className="full"><span>Contanos qué sucede</span><Textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Testigos encendidos, pérdida de potencia, falla intermitente..."/></label></div><button className="send-btn" onClick={send}>Enviar evaluación por WhatsApp <ArrowRight size={18}/></button><small>Esta solicitud no representa un precio definitivo.</small></DialogContent></Dialog>}
export default function Home(){const[menu,setMenu]=useState(false);const closeMenu=()=>setMenu(false);return <main><header className="nav"><a className="brand brand-logo" href="#top" onClick={closeMenu}><img src="https://res.cloudinary.com/dvvuwigmy/image/upload/v1788232533/IMG_1016_y4atye.jpg" alt="Autotrónica Go Diag"/></a><nav className={menu?"open":""}><a href="#especialidades" onClick={closeMenu}>Especialidades</a><a href="#trabajos" onClick={closeMenu}>Trabajos</a><a href="#metodo" onClick={closeMenu}>Método</a><a href="#certificaciones" onClick={closeMenu}>Certificaciones</a><a href="#contacto" onClick={closeMenu}>Contacto</a></nav><Quote label="Cotizar diagnóstico" className="nav-cta"/><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label={menu?"Cerrar menú":"Abrir menú"} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
<section className="hero video-hero" id="top"><video className="hero-video" autoPlay muted loop playsInline preload="auto" aria-hidden="true"><source src="https://res.cloudinary.com/dvvuwigmy/video/upload/f_mp4/v1788231305/InDown_jrusrr.mp4" type="video/mp4"/><source src="https://res.cloudinary.com/dvvuwigmy/video/upload/v1788231305/InDown_jrusrr.mov" type="video/quicktime"/></video><div className="hero-shade"/><div className="hero-copy"><div className="eyebrow"><span/> Ingeniería automotriz especializada · Caracas</div><h1>No cambiamos piezas.<br/><em>Encontramos la causa.</em></h1><p>Diagnóstico electrónico de precisión, reparación de módulos y calibración ECU para quienes necesitan una solución técnica, no una suposición.</p><div className="hero-actions"><Quote className="primary-btn"/><a href="#especialidades" className="text-link">Explorar capacidades</a></div><div className="proof-row"><div><b>Ingeniero</b><span>Mecánico certificado</span></div><div><b>12V / 24V</b><span>Livianos y pesados</span></div><div><b>Multimarca</b><span>Gasolina, diésel y EV</span></div></div></div></section>
<section className="brand-strip"><span>EXPERIENCIA MULTIMARCA</span>{brands.map(b=><b key={b}>{b}</b>)}</section>
<section className="services section" id="especialidades"><div className="section-heading"><div><span className="kicker">CAPACIDAD TÉCNICA</span><h2>Electrónica automotriz<br/>a nivel de ingeniería.</h2></div><p>Instrumentación avanzada, metodología y experiencia para intervenir sistemas que exigen diagnóstico real.</p></div><div className="service-grid">{services.map(({n,title,text,icon:Icon,image})=><article key={n} style={{backgroundImage:`linear-gradient(105deg,rgba(5,7,9,.97) 0%,rgba(5,7,9,.86) 47%,rgba(5,7,9,.5) 100%),url("${image}")`}}><div className="service-top"><span>{n}</span><Icon/></div><h3>{title}</h3><p>{text}</p><a href={`https://wa.me/${whatsapp}`} target="_blank">Consultar <ChevronRight size={15}/></a></article>)}</div></section>
<section className="work-section section" id="trabajos"><div className="section-heading work-heading"><div><span className="kicker">TRABAJO REAL · RESULTADOS REALES</span><h2>La precisión se<br/>demuestra trabajando.</h2></div><p>Una selección de intervenciones realizadas en diagnóstico, programación y reparación electrónica multimarca.</p></div><div className="work-grid">{works.map((work,i)=><article key={work.image} className={i===0||i===5?"work-wide":""}><img src={work.image} alt={work.title}/><div className="work-overlay"><span>{work.tag}</span><h3>{work.title}</h3><i>0{i+1}</i></div></article>)}</div><div className="work-proof"><div><b>Diagnóstico antes de reemplazar</b><span>Cada intervención comienza con mediciones y evidencia.</span></div><div><b>Equipamiento especializado</b><span>Escáner, osciloscopio y herramientas de programación.</span></div><a href="https://instagram.com/godiag.ve" target="_blank">Ver más trabajos <ArrowRight size={16}/></a></div></section>
<section className="method" id="metodo"><div className="method-visual"><div className="scope"><div className="scope-grid"/><svg viewBox="0 0 500 230" preserveAspectRatio="none"><path d="M0 150 C50 145 60 142 90 150 S140 160 175 146 L198 145 L218 45 L238 198 L259 144 L325 144 C350 144 360 115 380 142 S420 151 500 145"/></svg><span>OSCILLOSCOPE // CHANNEL A</span></div></div><div className="method-copy"><span className="kicker">DIAGNÓSTICO BASADO EN EVIDENCIA</span><h2>Medir. Interpretar.<br/>Resolver.</h2><p>Cada vehículo atraviesa un proceso ordenado para localizar la causa raíz antes de intervenir. Menos prueba y error. Más control.</p><ol><li><b>01</b><span><strong>Recepción técnica</strong>El síntoma y sus antecedentes.</span></li><li><b>02</b><span><strong>Pruebas & medición</strong>Escáner, osciloscopio y trazador.</span></li><li><b>03</b><span><strong>Informe & solución</strong>Explicación, alcance y recomendación.</span></li></ol></div></section>
<section className="expert section" id="certificaciones"><div className="expert-card"><div className="expert-media"><figure className="engineer-photo"><img src="https://res.cloudinary.com/dvvuwigmy/image/upload/v1788231287/IMG_1017_rx0uzq.jpg" alt="Ing. Elian González, especialista en autotrónica"/><figcaption>ING. ELIAN GONZÁLEZ</figcaption></figure><figure className="certificate-photo"><img src="https://res.cloudinary.com/dvvuwigmy/image/upload/v1788231283/IMG_1021_xsay5l.jpg" alt="Certificación profesional del Ing. Elian González"/><figcaption>FORMACIÓN CERTIFICADA</figcaption></figure></div><div className="expert-copy"><span className="kicker">INGENIERÍA · EXPERIENCIA · PRECISIÓN</span><h2>El conocimiento detrás del diagnóstico.</h2><p>Ingeniero mecánico con formación especializada y certificaciones técnicas en electrónica, diagnóstico y sistemas automotrices. Cada trabajo se sustenta en estudio, medición y procedimientos verificables.</p><div className="certs"><span><ShieldCheck/> Diagnóstico profesional</span><span><Microscope/> Instrumentación avanzada</span><span><Sparkles/> Actualización continua</span></div></div></div></section>
<section className="cta-section" id="contacto"><span className="kicker">TU VEHÍCULO MERECE CERTEZA</span><h2>Antes de reemplazar,<br/><em>diagnostiquemos.</em></h2><p>Contanos qué sucede y prepará la información de tu vehículo. Te orientamos sobre el próximo paso.</p><Quote label="Preparar mi evaluación" className="primary-btn"/><a className="phone" href={`tel:+${whatsapp}`}><Phone size={16}/> +58 422-2872237</a></section>
<footer><a className="brand brand-logo footer-logo" href="#top"><img src="https://res.cloudinary.com/dvvuwigmy/image/upload/v1788232533/IMG_1016_y4atye.jpg" alt="Autotrónica Go Diag"/></a><p>Diagnóstico preciso. Solución efectiva.</p><div><a href="https://instagram.com/godiag.ve" target="_blank">Instagram</a><a href={`https://wa.me/${whatsapp}`} target="_blank">WhatsApp</a><span>Caracas, Venezuela</span></div></footer><a className="floating-wa" href={`https://wa.me/${whatsapp}?text=${encodeURIComponent("Hola Autotrónica Go Diag. Quiero consultar por un diagnóstico.")}`} target="_blank" aria-label="Consultar por WhatsApp"><span><Phone size={20}/></span><b>CONSULTAR</b></a></main>}
